# Generated by Django 5.0 on 2025-04-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='tool',
            field=models.CharField(choices=[('image-captioning', 'Image Captioning'), ('image-generation', 'Image Generation'), ('phishing-detection', 'Phishing Detection'), ('other', 'Other')], default='other', max_length=255),
        ),
    ]
